spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/saat_teknoloji_db
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

omdb.api.url=http://www.omdbapi.com/
omdb.api.key=${OMDB_API_KEY}

spring.elasticsearch.uris=http://localhost:9200
spring.data.elasticsearch.repositories.enabled=true
