spring.application.name=core-service
spring.datasource.url=jdbc:postgresql://localhost:5432/saat_teknoloji_db
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

omdb.api.url=http://www.omdbapi.com/
omdb.api.key=${OMDB_API_KEY}

spring.elasticsearch.uris=http://localhost:9200
spring.data.elasticsearch.repositories.enabled=true


app.search.rrf.k=1
app.search.knn.candidates=100

app.search.rrf.weight.bm25=1.0
app.search.rrf.weight.vector=1.0

app.search.boost.title=3.0
app.search.boost.plot=1.5
app.search.boost.cast=1.0
app.search.boost.genre=1.0

app.search.query.minimum-should-match=1
app.search.expansion.min-word=3

spring.ai.ollama.embedding.options.model=all-minilm
spring.ai.ollama.chat.options.model=llama3.1:8b
spring.ai.ollama.chat.options.temperature=0.0

# CronJobs
jobs.cron.license-expiration=0 0 2 * * ?

# HIBERNATE BATCH
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

management.endpoints.web.exposure.include=health,prometheus
management.endpoint.health.show-details=always

server.port=8082
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

jwt.secret=${JWT_SECRET}
gateway.secret=${GATEWAY_SECRET}

app.storage.upload-dir=uploads
spring.servlet.multipart.max-file-size=6MB
spring.servlet.multipart.max-request-size=6MB
server.tomcat.max-swallow-size=-1

