FROM node:20-alpine as builder
WORKDIR /app


COPY saat-stream-client ./saat-stream-client
WORKDIR /app/saat-stream-client
RUN npm install
RUN npm run build -- --configuration production


WORKDIR /app
COPY frontend ./frontend
WORKDIR /app/frontend
RUN npm install
RUN npm run build -- --configuration production --base-href /admin/


FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf


COPY --from=builder /app/saat-stream-client/dist/saat-stream-client/browser /usr/share/nginx/html/stream
COPY --from=builder /app/frontend/dist/frontend/browser /usr/share/nginx/html/admin

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
