FROM node:20-alpine as builder
WORKDIR /app

# 1. Stream Client
COPY saat-stream-client ./saat-stream-client
WORKDIR /app/saat-stream-client
RUN npm install
RUN npm run build -- --configuration production

# 2. Admin Frontend
WORKDIR /app
COPY frontend ./frontend
WORKDIR /app/frontend
RUN npm install
RUN npm run build -- --configuration production --base-href /admin/

# 3. Auth UI
WORKDIR /app
COPY auth-ui ./auth-ui
WORKDIR /app/auth-ui
RUN npm install
RUN npm run build -- --configuration production --base-href /auth/

# Nginx
FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=builder /app/saat-stream-client/dist/saat-stream-client/browser /usr/share/nginx/html/stream
COPY --from=builder /app/frontend/dist/frontend/browser /usr/share/nginx/html/admin
COPY --from=builder /app/auth-ui/dist/auth-ui/browser /usr/share/nginx/html/auth

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
