server.port=8080

spring.application.name=api-gateway

eureka.client.serviceUrl.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

gateway.secret=${GATEWAY_SECRET:my-default-secret}

cors.allowed-origins=${CORS_ORIGINS:http://localhost:4200,http://localhost:4201,http://localhost:4202}
