version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: saat-tech-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: saat_teknoloji_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - saat-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: saat-tech-elastic
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    networks:
      - saat-network

  backend:
    build: .
    container_name: saat-tech-backend
    depends_on:
      - postgres
      - elasticsearch
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/saat_teknoloji_db
      - DB_USER=postgres
      - DB_PASSWORD=mysecretpassword
      - SPRING_ELASTICSEARCH_URIS=http://elasticsearch:9200
      - OMDB_API_KEY=${OMDB_API_KEY}
      - SPRING_AI_OLLAMA_BASE_URL=${OLLAMA_URL}
      - TMDB_API_KEY=${TMDB_API_KEY}
    ports:
      - "8080:8080"
    networks:
      - saat-network


  nginx-frontends:
    build:
      context: ../
      dockerfile: Dockerfile.frontends
    container_name: nginx-frontends
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - saat-network

volumes:
  postgres_data:
  elastic_data:

networks:
  saat-network:
    driver: bridge
